import { PropsWithChildren } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import '@repo/ui/globals.css';
import { Toaster } from 'sonner';
import Providers from './providers';
import {
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import { Button } from '@repo/ui/components/button';
import Link from 'next/link';
import { auth, currentUser } from '@clerk/nextjs/server';
import { getProfileByClerkId } from './api/profile';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default async function RootLayout({
  children,
}: Readonly<PropsWithChildren>) {
  const { userId, getToken } = await auth();
  const token = await getToken();
  let profileId;
  try {
    const { id } = await getProfileByClerkId(userId, token);
    profileId = id;
  } catch {
    // do nothing
  }
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <SignedOut>
              <SignInButton />
              <SignUpButton />
            </SignedOut>
            <SignedIn>
              { profileId ?
                <>
                  <Button asChild>
                    <Link href={`/profile/${profileId}`}>View Profile</Link>
                  </Button>
                  <Button asChild>
                    <Link href={`/profile/${profileId}/edit`}>
                      Edit Profile
                    </Link>
                  </Button>
                </> : null
              }
              <UserButton />
            </SignedIn>
          </header>
          {children}
          <Toaster />
        </body>
      </html>
    </Providers>
  );
}
